from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "8669381141a6"
down_revision: Union[str, None] = "b3cb6e940064"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("open_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("country", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("region", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("city", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("isp", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("device_model", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("os_name", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("browser_name", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("language", sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("open_events", schema=None) as batch_op:
        batch_op.drop_column("language")
        batch_op.drop_column("browser_name")
        batch_op.drop_column("os_name")
        batch_op.drop_column("device_model")
        batch_op.drop_column("isp")
        batch_op.drop_column("city")
        batch_op.drop_column("region")
        batch_op.drop_column("country")

    # ### end Alembic commands ###
