from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "b3cb6e940064"
down_revision: Union[str, None] = "e87081ab1b99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("open_events", schema=None) as batch_op:
        batch_op.drop_column("raw_headers")
        batch_op.drop_column("event_type")

    with op.batch_alter_table("tracked_emails", schema=None) as batch_op:
        batch_op.drop_column("notes")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracked_emails", schema=None) as batch_op:
        batch_op.add_column(sa.Column("notes", sa.TEXT(), nullable=True))

    with op.batch_alter_table("open_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_type", sa.VARCHAR(length=14), nullable=False))
        batch_op.add_column(sa.Column("raw_headers", sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
