from .density import DensityReport, EmailDensityOptimizer
from .engine import (
    format_email,
    generate_bimi_svg_ps,
    generate_document_preview_card,
    generate_plaintext_mirror,
)
from .mime import (
    decode_verp_address,
    encode_mime_body,
    encode_rfc2047_header,
    encode_verp_address,
    generate_archived_at_header,
    generate_arc_seal_headers,
    generate_arf_feedback_report,
    generate_authentication_results_header,
    generate_auto_submitted_headers,
    generate_autocrypt_headers,
    generate_cid_asset_headers,
    generate_dsn_recipient_headers,
    generate_enterprise_message_id,
    generate_feedback_id_headers,
    generate_imap_keyword_headers,
    generate_internationalized_headers,
    generate_mdn_suppression_headers,
    generate_mime_boundary,
    generate_reply_thread_headers,
    generate_resent_headers,
    generate_rfc2822_date,
    generate_webhook_signature_headers,
)
from .tags import (
    CAMOUFLAGE_PATTERNS,
    generate_tracking_tags,
    get_stealth_pixel_url,
    inject_tracking_tags,
    naturalize_text_entropy,
    wrap_link_cloaked,
    wrap_link_for_tracking,
)
from .types import EmailLink, EmailPayload
from .unsubscribe import (
    generate_rfc2369_headers,
    generate_unsubscribe_headers,
)

__all__ = [
    "EmailPayload",
    "EmailLink",
    "EmailDensityOptimizer",
    "DensityReport",
    "generate_mime_boundary",
    "encode_mime_body",
    "encode_rfc2047_header",
    "encode_verp_address",
    "decode_verp_address",
    "generate_autocrypt_headers",
    "generate_enterprise_message_id",
    "generate_rfc2822_date",
    "generate_feedback_id_headers",
    "generate_reply_thread_headers",
    "generate_resent_headers",
    "generate_authentication_results_header",
    "generate_imap_keyword_headers",
    "generate_internationalized_headers",
    "generate_mdn_suppression_headers",
    "generate_archived_at_header",
    "generate_arf_feedback_report",
    "generate_arc_seal_headers",
    "generate_cid_asset_headers",
    "generate_dsn_recipient_headers",
    "generate_auto_submitted_headers",
    "generate_webhook_signature_headers",
    "naturalize_text_entropy",
    "generate_unsubscribe_headers",
    "generate_rfc2369_headers",
    "format_email",
    "generate_plaintext_mirror",
    "generate_bimi_svg_ps",
    "generate_document_preview_card",
    "generate_tracking_tags",
    "inject_tracking_tags",
    "get_stealth_pixel_url",
    "wrap_link_for_tracking",
    "wrap_link_cloaked",
    "CAMOUFLAGE_PATTERNS",
]
